### ISSUE TITLE
demo dead 💀 

### ISSUE THREAD

**Issue by oswaldoacauan** [Rechdan/wyd-private-editors#2]

**Comment by Rechdan** [comment]
I'll fix that asap, thanks for the reminder!

**Comment by oswaldoacauan** [comment]
> I'll fix that asap, thanks for the reminder!

desistiu dos outros videos/conteudos de WYD?

**Comment by Rechdan** [comment]
> desistiu dos outros videos/conteudos de WYD?

Não é que desisti, mas sim to fora da área.

**Comment by Rechdan** [comment]
Demo is back online.
